"use client";

import { Document, Page, pdfjs } from "react-pdf";
import "react-pdf/dist/Page/AnnotationLayer.css";
import "react-pdf/dist/Page/TextLayer.css";

// Load the worker from a version-stamped static file in public/ (generated by
// scripts/copy-pdf-worker.mjs). This avoids bundler asset-URL resolution, which
// can 404 in a Next standalone/Turbopack production build and surface as
// "PDF preview failed". The version stamp keeps the worker in lockstep with the
// pdfjs API version that react-pdf imports here.
pdfjs.GlobalWorkerOptions.workerSrc = `/pdf.worker.${pdfjs.version}.min.mjs`;

export function PdfPreview({
  url,
  page,
  width,
  onPageCount,
  onError
}: {
  url: string;
  page: number;
  width: number;
  onPageCount: (count: number) => void;
  onError: (message: string) => void;
}) {
  return (
    <Document
      file={url}
      loading={<div className="h-96 animate-pulse rounded-md bg-slate-200 dark:bg-slate-800" />}
      error={<p className="p-4 text-sm text-red-700 dark:text-red-300">PDF preview failed.</p>}
      onLoadError={() => onError("PDF preview failed.")}
      onLoadSuccess={({ numPages }) => onPageCount(numPages)}
    >
      <Page
        pageNumber={page}
        width={width}
        renderAnnotationLayer={false}
        renderTextLayer={false}
        loading={
          <div className="h-96 animate-pulse rounded-md bg-slate-200 dark:bg-slate-800" />
        }
      />
    </Document>
  );
}
